version: 2
updates:
  - package-ecosystem: docker
    directory: /alpine-php-wordpress-amd64/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-php-wordpress-armhf/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-php-wordpress-aarch64/
    schedule:
      interval: weekly